import pandas as pd

country_iso3 = {
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American_Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antigua_and_Barbuda': 'ATG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Barbados': 'BRB',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia_(Plurinational_State_of)': 'BOL',
    'Bosnia_and_Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'British_Virgin_Islands': 'VGB',
    'Brunei_Darussalam': 'BRN',
    'Burkina_Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo_Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Cayman_Islands': 'CYM',
    'Central_African_Republic': 'CAF',
    'Chad': 'TCD',
    'Channel_Islands': 'CHI',  # This is a customary code; not an official ISO code
    'China,_Hong_Kong_SAR': 'HKG',
    'China,_Macao_SAR': 'MAC',
    'China,_mainland': 'CHN',
    'China,_Taiwan_Province_of': 'TWN',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Congo': 'COG',
    'Cook_Islands': 'COK',
    'Costa_Rica': 'CRI',
    "Côte_d'Ivoire": 'CIV',
    'Cuba': 'CUB',
    'Czechia': 'CZE',
    "Democratic_People's_Republic_of_Korea": 'PRK',
    'Democratic_Republic_of_the_Congo': 'COD',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican_Republic': 'DOM',
    'Ecuador': 'ECU',
    'El_Salvador': 'SLV',
    'Equatorial_Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Falkland_Islands_(Malvinas)': 'FLK',
    'Faroe_Islands': 'FRO',
    'Fiji': 'FJI',
    'French_Guiana': 'GUF',
    'French_Polynesia': 'PYF',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Honduras': 'HND',
    'Iceland': 'ISL',
    'Iran_(Islamic_Republic_of)': 'IRN',
    'Iraq': 'IRQ',
    'Isle_of_Man': 'IMN',
    'Jamaica': 'JAM',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    "Lao_People's_Democratic_Republic": 'LAO',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Luxembourg': 'LUX',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Maldives': 'MDV',
    'Malta': 'MLT',
    'Marshall_Islands': 'MHL',
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Micronesia_(Federated_States_of)': 'FSM',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Mozambique': 'MOZ',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands_Antilles_(former)': 'ANT',  # This is the former code for Netherlands Antilles
    'New_Caledonia': 'NCL',
    'New_Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Niue': 'NIU',
    'Norfolk_Island': 'NFK',
    'North_Macedonia': 'MKD',
    'Northern_Mariana_Islands': 'MNP',
    'Oman': 'OMN',
    'Palau': 'PLW',
    'Palestine': 'PSE',
    'Panama': 'PAN',
    'Papua_New_Guinea': 'PNG',
    'Pitcairn_Islands': 'PCN',
    'Puerto_Rico': 'PRI',
    'Qatar': 'QAT',
    'Republic_of_Korea': 'KOR',
    'Republic_of_Moldova': 'MDA',
    'Réunion': 'REU',
    'Russian_Federation': 'RUS',
    'Rwanda': 'RWA',
    'Saint_Helena,_Ascension_and_Tristan_da_Cunha': 'SHN',
    'Saint_Kitts_and_Nevis': 'KNA',
    'Saint_Lucia': 'LCA',
    'Saint_Pierre_and_Miquelon': 'SPM',
    'Saint_Vincent_and_the_Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San_Marino': 'SMR',
    'Sao_Tome_and_Principe': 'STP',
    'Saudi_Arabia': 'SAU',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra_Leone': 'SLE',
    'Singapore': 'SGP',
    'Solomon_Islands': 'SLB',
    'Somalia': 'SOM',
    'South Sudan': 'SSD',
    'South_Africa': 'ZAF',
    'Sri Lanka': 'LKA',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Switzerland': 'CHE',
    'Syrian Arab Republic': 'SYR',
    'Tajikistan': 'TJK',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States Virgin Islands': 'VIR',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Wallis and Futuna Islands': 'WLF',
    'Western Sahara': 'ESH',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Argentina': 'ARG',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Bangladesh': 'BGD',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Brazil': 'BRA',
    'Bulgaria': 'BGR',
    'Canada': 'CAN',
    'Chile': 'CHL',
    'China': 'CHN',  # Note: China is already present as 'China, mainland' in the original dictionary
    'Croatia': 'HRV',
    'Cyprus': 'CYP',
    'Denmark': 'DNK',
    'Egypt': 'EGY',
    'Estonia': 'EST',
    'Finland': 'FIN',
    'France': 'FRA',
    'Germany': 'DEU',
    'Greece': 'GRC',
    'Hungary': 'HUN',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Latvia': 'LVA',
    'Lithuania': 'LTU',
    'Malaysia': 'MYS',
    'Mali': 'MLI',
    'Mexico': 'MEX',
    'Morocco': 'MAR',
    'Myanmar': 'MMR',
    'Netherlands': 'NLD',
    'Nigeria': 'NGA',
    'Norway': 'NOR',
    'Pakistan': 'PAK',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Romania': 'ROU',
    'Senegal': 'SEN',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Thailand': 'THA',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'United Republic of Tanzania': 'TZA',
    'United States of America': 'USA',
    'Uruguay': 'URY',
    'Viet Nam': 'VNM'
}

# save the country_iso3 dictionary as a csv file with the column names "country" and "iso3"
pd.DataFrame(country_iso3.items(), columns=['country', 'iso3']).to_csv('data-clean/country_iso3.csv', index=False)